export interface Activity {
  amount: number;
  date: string;
  type: "received" | "sent" | "airdrop";
  coin: string;
  id: number;
  tokenId: string;
}

export const activities: Activity[] = [
  {
    amount: 10.9345,
    date: "Jun 9, 2025",
    type: "airdrop",
    coin: "BACH",
    id: 0,
    tokenId: "CTQBjyrX8pYyqbNa8vAhQfnRXfu9cUxnvrxj5PvbzTmf",
  },
  {
    amount: 100.0,
    date: "Jun 10, 2025",
    type: "received",
    coin: "BACH",
    id: 1,
    tokenId: "CTQBjyrX8pYyqbNa8vAhQfnRXfu9cUxnvrxj5PvbzTmf",
  },
  {
    amount: 50.0,
    date: "Jun 11, 2025",
    type: "sent",
    coin: "BACH",
    id: 2,
    tokenId: "CTQBjyrX8pYyqbNa8vAhQfnRXfu9cUxnvrxj5PvbzTmf",
  },
  {
    amount: 25.0,
    date: "Jun 12, 2025",
    type: "received",
    coin: "BACH",
    id: 3,
    tokenId: "CTQBjyrX8pYyqbNa8vAhQfnRXfu9cUxnvrxj5PvbzTmf",
  },
  {
    amount: 10.0,
    date: "Jun 13, 2025",
    type: "sent",
    coin: "BACH",
    id: 4,
    tokenId: "CTQBjyrX8pYyqbNa8vAhQfnRXfu9cUxnvrxj5PvbzTmf",
  },
  {
    amount: 5.0,
    date: "Jun 14, 2025",
    type: "received",
    coin: "USDC",
    id: 5,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 2.5,
    date: "Jun 15, 2025",
    type: "sent",
    coin: "USDC",
    id: 6,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 1.25,
    date: "Jun 16, 2025",
    type: "received",
    coin: "USDC",
    id: 7,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 0.625,
    date: "Jun 17, 2025",
    type: "sent",
    coin: "USDC",
    id: 8,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 0.3125,
    date: "Jun 18, 2025",
    type: "received",
    coin: "USDC",
    id: 9,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 0.15625,
    date: "Jun 19, 2025",
    type: "sent",
    coin: "USDC",
    id: 10,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 0.078125,
    date: "Jun 10, 2025",
    type: "received",
    coin: "BACH",
    id: 11,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 50.0,
    date: "Jun 11, 2025",
    type: "sent",
    coin: "BACH",
    id: 12,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 25.0,
    date: "Jun 12, 2025",
    type: "received",
    coin: "BACH",
    id: 13,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 10.0,
    date: "Jun 13, 2025",
    type: "sent",
    coin: "BACH",
    id: 14,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 5.0,
    date: "Jun 14, 2025",
    type: "received",
    coin: "USDC",
    id: 15,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 1.25,
    date: "Jun 16, 2025",
    type: "received",
    coin: "USDC",
    id: 16,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 0.625,
    date: "Jun 17, 2025",
    type: "sent",
    coin: "USDC",
    id: 17,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 0.3125,
    date: "Jun 18, 2025",
    type: "received",
    coin: "USDC",
    id: 18,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  {
    amount: 0.15625,
    date: "Jun 19, 2025",
    type: "sent",
    coin: "USDC",
    id: 19,
    tokenId: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
];
